- role: "Guest Editor"
  organization: "Journal of Real Estate Research"
  period: "2025"
  url: "https://www.tandfonline.com/journals/rjer20/about-this-journal"
- role: "Editorial Board"
  organization: "Journal of Real Estate Research"
  period: "2023–present"
  url: "https://www.tandfonline.com/journals/rjer20/about-this-journal"
- role: "Editorial Board"
  organization: "Journal of Real Estate Portfolio Management"
  period: "2024–present"
  url: "https://www.tandfonline.com/journals/repm20/about-this-journal"
- role: "Editorial Board"
  organization: "Journal of Real Estate Practice and Education"
  period: "2024–present"
  url: "https://www.tandfonline.com/journals/rjrp20/about-this-journal"
- role: "Board of Directors"
  organization: "Asian Real Estate Society"
  period: "2024–present"
  url: "https://www.asres.org/boardOfdirectors.html"
